# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Lucifer.dark/Desktop/Lab04/Lab04.srcs/sources_1/ip/Mem/Mem.xci
# IP: The module: 'Mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Lucifer.dark/Desktop/Lab04/Lab04.srcs/sources_1/ip/Mem/Mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Lucifer.dark/Desktop/Lab04/Lab04.srcs/sources_1/ip/Mem/Mem.xci
# IP: The module: 'Mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Lucifer.dark/Desktop/Lab04/Lab04.srcs/sources_1/ip/Mem/Mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
